workflows:
  build-android-apk:
    name: Build Android APK
    max_build_duration: 45
    environment:
      vars:
        KEYSTORE_PASSWORD: $KEYSTORE_PASSWORD
        KEY_ALIAS: $KEY_ALIAS
        KEY_PASSWORD: $KEY_PASSWORD
      java: 17
      node: 16
    scripts:
      - name: Print environment variables
        script: |
          echo "Keystore password: $KEYSTORE_PASSWORD"
          echo "Alias: $KEY_ALIAS"
          echo "Key password: $KEY_PASSWORD"
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - toshisharma7412@gmail.com
