workflows:
  build-android-apk:
    name: Build Android APK
    max_build_duration: 45
    environment:
      vars:
        KEYSTORE_PASSWORD: $KEYSTORE_PASSWORD
        KEY_ALIAS: $KEY_ALIAS
        KEY_PASSWORD: $KEY_PASSWORD
      java: 17
      node: 16
    scripts:
      - name: setup path for NDK
        script: |
          export ANDROID_HOME=/usr/local/share/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
      - name: Clean and prepare environment
        script: |
          rm -rf android/build/generated/autolinking/autolinking.json
          cd android
          ./gradlew clean
          cd ..
          rm -rf node_modules
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - toshisharma7412@gmail.com
