workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    scripts:
      - name: Install dependencies via Yarn
        script: echo "this is test"
