workflows:
  build-android-apk:
    name: Build Android APK
    max_build_duration: 45
    environment:
      vars:
        KEYSTORE_PASSWORD: $KEYSTORE_PASSWORD
        KEY_ALIAS: $KEY_ALIAS
        KEY_PASSWORD: $KEY_PASSWORD
      java: 17
      node: 16
    scripts:
      - name: Setup Android SDK path
        script: |
          export ANDROID_HOME=/usr/local/share/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
      - name: Clean and install dependencies
        script: |
          rm -rf node_modules android/build
          npm install
      - name: Generate autolinking config
        script: |
          npx react-native config
      - name: Build Android APK
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - toshisharma7412@gmail.com
